### ISSUE TITLE
Message: Undefined index: default - Line Number: 267

### ISSUE THREAD

**Issue by petenice** [clickrain/switch#9]
Added Switch to Grid field, system shows error.

A PHP Error was encountered
Severity: Notice
Message: Undefined index: default
Filename: switch/ft.switch.php
Line Number: 267

EE v2.9.2 - Build Date: 20141004 

Commented out following lines, error went away

```
    // If this is a new entry, use the default.
    /*
    if ($rowid === 'new') {
        $data = $this->settings['default'];
    }
    */
```

**Comment by petenice** [comment]
![view](https://cloud.githubusercontent.com/assets/254627/5419794/977c8078-8203-11e4-86cf-3f13bff4a31d.png)

**Comment by bryanburgers** [comment]
Interesting. Can you `var_dump` the settings and post what actually is in there?

**Comment by petenice** [comment]
Am I doing this right? Here's code and results.

```
    // If this is a new entry, use the default.

    if ($rowid === 'new') {
        $data = $this->settings['default'];
        var_dump($this->settings);
    }
```

A PHP Error was encountered
Severity: Notice
Message: Undefined index: default
Filename: switch/ft.switch.php
Line Number: 268
array(33) { ["options"]=> string(1) "2" ["label1"]=> string(3) "OFF" ["value1"]=> string(0) "" ["color1"]=> string(3) "red" ["label2"]=> string(2) "ON" ["value2"]=> string(4) "star" ["color2"]=> string(5) "green" ["label3"]=> string(3) "OFF" ["value3"]=> string(0) "" ["color3"]=> string(7) "default" ["label4"]=> string(3) "OFF" ["value4"]=> string(0) "" ["color4"]=> string(7) "default" ["label5"]=> string(3) "OFF" ["value5"]=> string(0) "" ["color5"]=> string(7) "default" ["label6"]=> string(3) "OFF" ["value6"]=> string(0) "" ["color6"]=> string(7) "default" ["label7"]=> string(3) "OFF" ["value7"]=> string(0) "" ["color7"]=> string(7) "default" ["label8"]=> string(3) "OFF" ["value8"]=> string(0) "" ["color8"]=> string(7) "default" ["field_required"]=> string(1) "n" ["field_label"]=> string(4) "Star" ["col_id"]=> string(2) "13" ["col_name"]=> string(10) "htile_star" ["col_required"]=> string(1) "n" ["entry_id"]=> string(3) "137" ["grid_field_id"]=> string(2) "49" ["grid_row_name"]=> NULL }

**Comment by petenice** [comment]
Thank you!
